using System.Runtime.Serialization;

namespace XBMCRPC.Addon
{
   public enum Types
   {
       unknown,
       [EnumMember(Value="xbmc.metadata.scraper.albums")]
       Xbmc_metadata_scraper_albums,
       [EnumMember(Value="xbmc.metadata.scraper.artists")]
       Xbmc_metadata_scraper_artists,
       [EnumMember(Value="xbmc.metadata.scraper.movies")]
       Xbmc_metadata_scraper_movies,
       [EnumMember(Value="xbmc.metadata.scraper.musicvideos")]
       Xbmc_metadata_scraper_musicvideos,
       [EnumMember(Value="xbmc.metadata.scraper.tvshows")]
       Xbmc_metadata_scraper_tvshows,
       [EnumMember(Value="xbmc.ui.screensaver")]
       Xbmc_ui_screensaver,
       [EnumMember(Value="xbmc.player.musicviz")]
       Xbmc_player_musicviz,
       [EnumMember(Value="xbmc.python.pluginsource")]
       Xbmc_python_pluginsource,
       [EnumMember(Value="xbmc.python.script")]
       Xbmc_python_script,
       [EnumMember(Value="xbmc.python.weather")]
       Xbmc_python_weather,
       [EnumMember(Value="xbmc.python.subtitles")]
       Xbmc_python_subtitles,
       [EnumMember(Value="xbmc.python.lyrics")]
       Xbmc_python_lyrics,
       [EnumMember(Value="xbmc.gui.skin")]
       Xbmc_gui_skin,
       [EnumMember(Value="xbmc.gui.webinterface")]
       Xbmc_gui_webinterface,
       [EnumMember(Value="xbmc.pvrclient")]
       Xbmc_pvrclient,
       [EnumMember(Value="xbmc.addon.video")]
       Xbmc_addon_video,
       [EnumMember(Value="xbmc.addon.audio")]
       Xbmc_addon_audio,
       [EnumMember(Value="xbmc.addon.image")]
       Xbmc_addon_image,
       [EnumMember(Value="xbmc.addon.executable")]
       Xbmc_addon_executable,
       [EnumMember(Value="xbmc.service")]
       Xbmc_service,
       [EnumMember(Value="xbmc.subtitle.module")]
       Xbmc_subtitle_module
   }
}
